apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-api-gateway
  labels:
    app: forex-api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forex-api-gateway
  template:
    metadata:
      labels:
        app: forex-api-gateway
    spec:
      containers:
        - name: forex-api-gateway
          image: forex-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "8000"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: forex-secrets
                  key: jwt-secret
            - name: REDIS_URL
              value: "redis://forex-redis:6379"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: forex-secrets
                  key: database-url
            - name: FRONTEND_URL
              value: "http://forex-frontend:3000"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: forex-api-gateway
  labels:
    app: forex-api-gateway
spec:
  selector:
    app: forex-api-gateway
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
