apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-frontend
  labels:
    app: forex-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: forex-frontend
  template:
    metadata:
      labels:
        app: forex-frontend
    spec:
      containers:
        - name: forex-frontend
          image: forex-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://forex-api-gateway:8000"
            - name: REACT_APP_WS_URL
              value: "ws://forex-websocket:8001"
            - name: REACT_APP_BIAS_API_URL
              value: "http://forex-backend:8080"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: forex-frontend
  labels:
    app: forex-frontend
spec:
  selector:
    app: forex-frontend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
